name: ArenaSystem
version: ${project.version}
main: lol.maltest.arenasystem.ArenaSystem
authors: [ maltest, TheRealDan, ggtylerr ]
description: Arena system
depend: ['WorldEdit']
commands:
  testpaste:
    description: Testing schematic stuff
  makevoid:
    description: make void