name: ArenaSystem
version: ${project.version}
main: lol.maltest.arenasystem.ArenaSystem
authors: [ mal, TheRealDan ]
description: Arena system
depend: ['WorldEdit']
commands:
  testpaste:
    description: Testing schematic stuff
  pasteschem:
    description: LOl